### ISSUE TITLE
Rust - FgbReader way to reset Iterator or maybe split Iterator from FgbReader

### ISSUE THREAD

**Issue by apps4uco** [flatgeobuf/flatgeobuf#101]
My use case is to open one FgbReader and have multiple queries with the same FlatGeoBuffer

This could just be a documentation problem, I could not find a way to reset the iterator.

Is there a way to reset the iterator to the start, apart from creating a FgbReader again, which will read the data for a second time.

Or what about a method
FgbReader::iter() that returns a FallibleStreamingIterator

**Comment by pka** [comment]
`FgbReader` holds the reading state, so it can't be used in parallel. Currently, you have to use multiple `FgbReader` instances for that. An external iterator would be a nicer solution, I agree. PR welcome!

**Comment by pka** [comment]
In the meantime, FgbReader consumes `self` when an iterable state is reached. It would be a fundamental redesign to support external iterators.
