### ISSUE TITLE
Error on Safari: `ReferenceError: Can't find variable: BigUint64Array`

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#115]
Currently the examples don't work for me on Safari 14.0.3 (latest currently available): https://flatgeobuf.org/examples/leaflet/index.html

Console output:
```
[Error] ReferenceError: Can't find variable: BigUint64Array
	(anonymous function) (flatgeobuf-geojson.min.js:1:19960)
	(anonymous function) (flatgeobuf-geojson.min.js:1:142)
	Global Code (flatgeobuf-geojson.min.js:1:212)
[Error] Unhandled Promise Rejection: TypeError: flatgeobuf.deserialize is not a function. (In 'flatgeobuf.deserialize(response.body, undefined, handleHeaderMeta)', 'flatgeobuf.deserialize' is undefined)
	handleResponse (index.js:22)
	promiseReactionJob
```

BigUint64Array is not currently supported on Safari (including iOS): https://caniuse.com/?search=BigUint64Array

**Comment by michaelkirk** [comment]
Apparently this is implemented, but not yet released:
 
Implement BigInt64Array and BigUint64Array:
https://bugs.webkit.org/show_bug.cgi?id=190800


committed: 
https://trac.webkit.org/changeset/272170/webkit


The good news is that I just tried it in https://developer.apple.com/safari/technology-preview/ and it works. I don't know when this will reach mainline though, and even when it is released, it'll be a while before it rolls out to users. It'd be nice if there were some kind of fallback for older Safari/iOS.

**Comment by bjornharrtell** [comment]
Thanks for reporting, I was not aware and would like to find out why it is used. But perhaps it can be polyfilled?

**Comment by michaelkirk** [comment]
It looks like it's only used in https://github.com/flatgeobuf/flatgeobuf/blob/ee6548d/src/ts/ColumnMeta.ts#L12
```
const arrayTypeMap = {                     
    [ColumnType.Byte]: Uint8Array,         
    [ColumnType.UByte]: Uint8Array,        
    [ColumnType.Bool]: Uint8Array,         
    [ColumnType.Short]: Uint16Array,       
    [ColumnType.UShort]: Uint16Array,      
    [ColumnType.Int]: Uint32Array,         
    [ColumnType.UInt]: Uint32Array,        
    # Used here
    [ColumnType.Long]: BigUint64Array,     
    # Used here
    [ColumnType.ULong]: BigUint64Array,    
    [ColumnType.Float]: Float64Array,      
    [ColumnType.Double]: Float64Array,     
    [ColumnType.String]: String,           
    [ColumnType.Json]: String,             
    [ColumnType.DateTime]: String,         
    [ColumnType.Binary]: String
} 
```

I think this means, if your feature data includes Long/ULong, it's mapped to this type.

**Comment by michaelkirk** [comment]
There is a pure-js implementation of BigNum which might be useful.

https://github.com/GoogleChromeLabs/jsbi/issues/4

Only problem is it *also* seems to not implement 64bit handling 😓, but there is a (stalled?) PR which seems to work towards that:

https://github.com/GoogleChromeLabs/jsbi/pull/18

**Comment by bjornharrtell** [comment]
Hmm funky.. I've completely forgot what I'm using that array type for. 😆

**Comment by bjornharrtell** [comment]
Hmm I made use of it when refactoring property encoding in https://github.com/flatgeobuf/flatgeobuf/pull/63. I wanted to avoid having to preallocate... the complexity of it is a bit too much though now that I look at it again. But not sure if I can figure out a better approach.

**Comment by bjornharrtell** [comment]
Reworked with https://github.com/flatgeobuf/flatgeobuf/commit/08f85cff7811259e2ea33c43a155f3bf789fd13f so that it could be removed with https://github.com/flatgeobuf/flatgeobuf/commit/c57150181ea148199fbeba131d0bb7f40cc5a588.

**Comment by michaelkirk** [comment]
Verified that this fixes things for me. Thanks!
