### ISSUE TITLE
revamp JS examples

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#118]
- [ ] Include examples which run off the local build (i'm tired of having to always modify them to point to my local 😆)
- [x] make it easier to discover all the other examples - e.g. a meta-index which links to all of the examples.
  - full file
  - search
  - for both leaflet and open layers

Also, as the JS i/o gets better (#50), it might be neat to post slightly different examples:
- [x] search a *very large* file - I have such a file. Would you be interested in moving it to the fgb s3 bucket?
- [x] dynamic search (e.g. drag a bounding rect around)

**Comment by michaelkirk** [comment]
I'm happy to do this work - just wanted to run it by y'all to see if you had any thoughts.

**Comment by bjornharrtell** [comment]
Good ideas. I'll be happy to support/help out and if possible it would be great to put up an example of huge file bbox search.

**Comment by tim-salabim** [comment]
If at all possible, it would be great to re-visit the leaflet example. @bjornharrtell pointed out to me once that there may be better implementations than the current example. We rely on this example quite heavily in the leafem R package. Even though the approach seems to work very nicely and is robust, I am always interested in improvements. Thanks again for all the great work here!!

**Comment by michaelkirk** [comment]
@tim-salabim, for this particular issue, I'm only intending to work on showing off what the library can already do.

I think you might be talking about #23, which indeed sounds interesting!

**Comment by tim-salabim** [comment]
@michaelkirk thanks for the heads-up. Yes, I am particularly interested in a performant leaflet binding for our very narrow use-case of data interchange between R and browser (for the vis). I'd like to emphazise though, that I am already very happy with the current implementation! So no worries really

**Comment by bjornharrtell** [comment]
I have thrown togheter an example "openlayers-hnv". When zoomed in quite far it attempts to request bbox filtered from google cloud cloud storage from a 3.4 GB FlatGeobuf, unfortunately it's not going well. I get network requests like this:

![image](https://user-images.githubusercontent.com/141030/117180891-f4ffaa00-add4-11eb-89cc-28c238a90d26.png)

And it seem to continue indefinitely with 131 kB large bits.

Note that it uses a local build from master. I'll dig into it a bit when I have time, but wanted to give you heads up @michaelkirk.

**Comment by bjornharrtell** [comment]
@michaelkirk nevermind! It was my mistake, the rect argument was all wrong.

**Comment by bjornharrtell** [comment]
So with https://github.com/flatgeobuf/flatgeobuf/commit/2eb86b9a188fb942455b4eed978b4702b625bcce it seems to work but I still see that the last few requests are 131 kB which is both curious and seem exessive.

**Comment by bjornharrtell** [comment]
Tried to reproduce with local tests added with https://github.com/flatgeobuf/flatgeobuf/commit/afa2a00e13dc9f350e4d7d5b6d6778ec0223570b but cannot, so I'm not at all sure why I'm seeing that kind of traffic in the browser example.

**Comment by bjornharrtell** [comment]
Ah no I *can* reproduce it. Logging reveals that the feature data request is the 131 kB long one:

yielding feature
need Range: 195639128-195639131
request: #5, purpose: feature length), bytes: (this_request: 131072, ever: 151096), Range: bytes=195639128-195770199

So perhaps this is the intended behaviour? A bit large buffer perhaps.

**Comment by bjornharrtell** [comment]
Ahh.. https://github.com/flatgeobuf/flatgeobuf/blob/afa2a00e13dc9f350e4d7d5b6d6778ec0223570b/src/ts/HttpReader.ts#L125 :)

**Comment by michaelkirk** [comment]
Ah yes, sorry for any confusion there.

I set a smallish min requests size for feature data because I was kind of horrified to see our JS examples go from hundred kb of transfer to 3MB or so...

We could change that constant, or make it configurable.

Or, with more effort, I'm considering utilizing the index to get more right-sized feature requests...

**Comment by bjornharrtell** [comment]
Agreed it's very data and use case dependent and heuristics could become very complex.. although GDAL has a simple double size if sequential access is detected and it's not too bad.

**Comment by bjornharrtell** [comment]
I think we should start with making it an optional parameter, and I think the default should be lower fx. 8 kB.

**Comment by michaelkirk** [comment]
I think this can be closed as of #120. More perf work ideas in #122
