### ISSUE TITLE
js: Safari doesn't support 64bit integer columns (Long/ULong)

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#127]
`Long`/`ULong` columns deserialize by using `n.getBigInt64`/`n.getBigUInt64`, neither of those methods are supported on the latest stable Safari on macOS (Version 14.1.1 (16611.2.7.1.4)) nor on iOS.

<img width="783" alt="Screen Shot 2021-05-31 at 4 43 21 PM" src="https://user-images.githubusercontent.com/217057/120249325-57f72c00-c22f-11eb-8ee3-5baa8cc3f4f2.png">

> In 'n.getBigInt64(a,!0)', 'n.getBigInt64' is undefined)

https://caniuse.com/mdn-javascript_builtins_dataview_getbigint64
https://caniuse.com/mdn-javascript_builtins_dataview_getbiguint64

Note that both methods *are* supported on the latest Safari Technology Preview: Release 125 (Safari 14.2, WebKit 16612.1.15.1.12)

This is somewhat related to https://github.com/flatgeobuf/flatgeobuf/issues/115. Prior to that, Safari couldn't use FGB at all - now the situation is that you *can* use FGB on Safari, provided you don't have any 64bit integer columns.

**Comment by bjornharrtell** [comment]
Looks like it has been supported for some time now.
