### ISSUE TITLE
not in the streaming way when reading local files?

### ISSUE THREAD

**Issue by kkdd** [flatgeobuf/flatgeobuf#128]
Hello,
I realized that flatgeobuf treats data not in the streaming way but the batch way when reading local files. Isn't it the matter of flatgeobuf, however?

See an example examined:

* [Leaflet map: read flatgeobuf files by dropping-on](https://bl.ocks.org/kkdd/d18eb75331b2271ca9ab0b0e13be20d6) (bl.ocks.org)

And an example source:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Leaflet</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css">
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
		<script src="https://unpkg.com/flatgeobuf@3.17.3/dist/flatgeobuf-geojson.min.js"></script>
	<style>
		body { margin:0; padding:0; }
		#map { position:absolute; top:0; bottom:0; width:100%; }
	</style>
</head>
<body>
<div id='map'></div>
<script>
	const map = L.map('map').setView([40, -80], 2);
	L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
	}).addTo(map);

	const dropArea = document.getElementById('map');
	dropArea.ondragover = () => false;
	dropArea.ondragend = () => false;
	dropArea.ondrop = event => {
		Array.prototype.forEach.call(event.dataTransfer.files, readFlatGeoBuf);
		event.preventDefault();
		return false;
	};

	const readFlatGeoBuf = file => {
		const it = flatgeobuf.deserialize(file.stream(), undefined);
		(async () => { 
			for await (const feature of it) {
				L.geoJSON(feature).addTo(map);
			}
		})();
	}
</script>
</body>
</html>
```

**Comment by bjornharrtell** [comment]
That looks streaming / non-batch to me. If you do not agree, please try to explain better.

**Comment by kkdd** [comment]
This is the behavior result by using ```UScounties.fgb```:

![output](https://user-images.githubusercontent.com/5372642/120660653-82144c80-c4c2-11eb-8d68-5e82c4bdb386.gif)

**Comment by bjornharrtell** [comment]
Ok, I don't know. Perhaps something specific in how a stream from drag and drop works.

**Comment by kkdd** [comment]
Thank you for your comment.
I think that It doesn't seem to be the matter of flatgeobuf.

**Comment by kkdd** [comment]
Drawing in the streaming way is finally achieved by inserting ```await wait()``` as follows:

```javascript
for await (const features of iter) {
  await wait(); // inserted
  drawFeatures(features);
}
```

in "[Leaflet map: read GeoJSONL/flatgeobuf files by dropping-on](https://bl.ocks.org/kkdd/d18eb75331b2271ca9ab0b0e13be20d6)" (bl.ocks.org).

![bc2e29c5-3693-b178-5966-b70be1944c17](https://user-images.githubusercontent.com/5372642/147400889-df09fee2-d937-479c-ab95-9414f24ff6eb.gif)

**Comment by bjornharrtell** [comment]
What does wait do? 😂

**Comment by kkdd** [comment]
Sorry for missing the definition of ```wait()```, which is

```javascript
const wait = () => new Promise(resolve => setTimeout(resolve, 0));
```

**Comment by bjornharrtell** [comment]
Then I would think that it is simply a matter of the process happening so fast so that it will not have time to update the visual before it is completed.
