### ISSUE TITLE
Add GeoTools DataStore

### ISSUE THREAD

**Issue by jericks** [flatgeobuf/flatgeobuf#15]
I am interested in adding a Geotools DataStore that would be able to read and write flatgeobuf files.  I am working on a Geotools pull request:

https://github.com/jericks/geotools/commit/fc4dc88230f7675058ff248f479c7f753460a083

but I was wondering if you would like this done as a GeoTools modules or in this repository.

**Comment by jericks** [comment]
Here is the GeoTools pull request: https://github.com/geotools/geotools/pull/2689.

Since, GeoTools reads and writes one feature at a time, I had to borrow a few private methods.  Could we update the Java API so I can delete the duplicated code?

**Comment by bjornharrtell** [comment]
I think having it done as a GeoTools module is preferable. I'd like to put more work into the Java API ASAP and I'll see what I can do about the situation with the duplicate code.

**Comment by bjornharrtell** [comment]
The possible reuse I could find are MAGIC_BYTES and buildHeader which I've worked on in https://github.com/bjornharrtell/flatgeobuf/pull/16. @jericks, did I miss something?

**Comment by jericks** [comment]
This looks really good.  The GeoTools DataStore needs a way to read the FeatureType and then read the Features one at a time, which requires keeping track of the offset and the HeaderMeta (https://github.com/geotools/geotools/pull/2689/files#diff-c08398299915f1aadc69c070384e0ebbR156).  I was thinking of introducing a FeatureTypeConversions class with serialize and deserialize methods and then adding featureType and offset properties to the HeaderMeta class.  I could work on a pull request if you think this sounds reasonable.

**Comment by bjornharrtell** [comment]
Sure, pull requests are welcome.

**Comment by bjornharrtell** [comment]
Implemented in geotools since quite some time, see https://osgeo-org.atlassian.net/browse/GEOT-6866.
