### ISSUE TITLE
OL & Leaflet Support

### ISSUE THREAD

**Issue by SpatialJ** [flatgeobuf/flatgeobuf#168]
Hi,
the examples given for ol and leaflet seems to throw away all previoulsy fecthed features when panning. Was that a deisgn decision or just due to the simplicity of the clientside code?
Is the code available that keeps already fetched features?

Best,
Johannes

**Comment by bjornharrtell** [comment]
I would say that is just for example simplicity. If you keep data cached client side you get new problems to solve:

1. How long do you keep it cached?
2. How large amount is reasonable to cache at client side?
3. How to track and evict cache?

Those problems are general and have nothing to do with the data format.
