### ISSUE TITLE
"viewer" example doesn't work on safari (CORS)

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#177]
This is more of a deployment issue, and not a bug in FGB,  but not sure where else to report it.

The new example at https://flatgeobuf.org/examples/viewer/ doesn't work on safari.

<img width="833" alt="Screen Shot 2022-03-02 at 11 19 19 AM" src="https://user-images.githubusercontent.com/217057/156433118-6ba8986f-7fc7-459d-9ed6-954fb4d0b571.png">

FWIW, it seems like the CDN where the resources for the [other examples](https://flatgeobuf.org/examples/leaflet/large.html) are stored is responding appropriately. One easy fix might be to move the resource to the same CDN.

**Comment by bjornharrtell** [comment]
Done, and much faster now too. :)
