### ISSUE TITLE
NET: Implementation of CoordinateSequence for FlatGeobuf needs proper Copy method

### ISSUE THREAD

**Issue by FObermaier** [flatgeobuf/flatgeobuf#180]
The current implementation of `CoordinateSequence` for FlatGeobuf needs a proper `CoordinateSequence.Copy` method. Without it, calls to `Geometry.Copy()` return empty geometries.

**Comment by FObermaier** [comment]
@bjornharrtell, I'm sorry but the initial implementation is buggy for multi-part geometries due to wrong offset for System.Buffers.Copy(...).

**Comment by bjornharrtell** [comment]
@FObermaier does it make sense to reopen this or treat as new bug?

**Comment by FObermaier** [comment]
I think that this will do
