### ISSUE TITLE
NET: Serializing Attribute of type AttributesTable returns Unknown type from ToColumnType. 

### ISSUE THREAD

**Issue by ptrefall** [flatgeobuf/flatgeobuf#188]
Hi,

I'm converting GeoJson strings to NTS.Features, and then I try to serialize the FeatureCollection to a byte array.

I use NetTopologySuite.IO.GeoJsonReader, and successfully convert a GeoJson string to NTS.Feature, then add it to a FeatureCollection.
I then try to serialize the FeatureCollection using FlatGeobuf.NTS.FeatureCollectionConversions's Serialize, which throws the "Unknown type" exception. This happens because the Feature holds an Attribute {[UtmPosition, {NetTopologySuite.Features.AttributesTable}]}.

Is there anything I'm doing wrong here in the conversion process or conversion process, or is there any work-around for me to handle this "ColumnType" manually?

Thank you for any help on the matter.

**Comment by bjornharrtell** [comment]
@ptrefall the supported column types of FlatGeobuf are well known primitive types and the current C# implementation is constraining a bit further (see https://github.com/flatgeobuf/flatgeobuf/blob/4ec18468be580061ff0ca1d204ea352c8abb0c2e/src/net/FlatGeobuf/NTS/FeatureConversions.cs#L39-L57). Regardless, there is no way FlatGeobuf can support custom objects like "UtmPosition", it needs to be converted into a primitive type to be serializable, for example a string. Does that make sense to you? Else I can perhaps reprhase or explain in another way. :)
