### ISSUE TITLE
private types make it impossible to return or store `FgbReader`

### ISSUE THREAD

**Issue by msalib** [flatgeobuf/flatgeobuf#193]
`FgbReader` has a generic parameter for `State` but since `State` is private, there's no way to write a function that returns an `FgbReader`, nor can you stash it in a struct. That's a bit of a usability problem. Making the `reader_state` module (or better yet a proper enum) public would fix the issue!

**Comment by bjornharrtell** [comment]
I assume this is about the Rust implementation?

**Comment by pka** [comment]
This sounds like a serious usability problem. I tried to hide the state as much as possible, since it's only used to help the compiler detecting wrong API usage. I wonder if a public type alias would also solve the problem?

**Comment by msalib** [comment]
Yes, this is about the Rust implementation!
