### ISSUE TITLE
build scripts and docs for cpp

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#194]
I wanted to compare some behavior of the rust writer implementation to the cpp implementation, but I was unable to find any documentation or configuration to build the cpp implementation. 

I know that there is build support for the version [embedded in GDAL](https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/flatgeobuf), but it seems desirable that it can be built and tested in a stand alone way. 

What do you think? Is this something that you have locally @bjornharrtell? Would you be willing to share and commit it to this repo?

Otherwise, I can cobble something together. Would you be interested in a PR?

**Comment by bjornharrtell** [comment]
Not exactly sure what you mean. I will say that the reference cpp implementation is a bit forgotten and not in an as complete state as I would like to. But it is built and tested as part of CI at https://github.com/flatgeobuf/flatgeobuf/blob/baad79daa83614ba995d50c7e31f22c21397c51e/.circleci/config.yml#L87-L88.

There is really not much more than the generated headers and the packedrtree implementation. The geojson bit is more or less only made as a rough example and to support the testcases. In a real world application you would likely want to use the headers directly to avoid the overhead of transforming to a geojson representation. A more high level API would be nice but I got kind of stuck on the point that I couldn't find a suitable high level geometry/feature api to base it on.
