### ISSUE TITLE
Proper way to persist and recover data from disk

### ISSUE THREAD

**Issue by ghost** [flatgeobuf/flatgeobuf#220]
I tried several hacks on the result buffer of `serialize` with no luck. Is there an API for persisting/recovering data ?
`serialize` returns `Uint8Array` so this is how I'm persisting it:

```js
const flatgeobuf = serialize(fileContent)
fs.appendFileSync(path.join(__dirname, '../data/geo/states.fgb'), Buffer.from(flatgeobuf));
```

But I cannot recover the model (only errors)!

```js
const pickle = fs.readFileSync(path.join(__dirname, '../data/geo/states.fgb'))
// 1
// const ab = new ArrayBuffer(pickle.length);
// const view = new Uint8Array(ab);
// 2
// deserialize(pickle)
// 3
const view = new Uint8Array(pickle.buffer);
deserialize(view)
```
All don't work.

Thanks a lot !!

**Comment by bjornharrtell** [comment]
Not sure what is going on there but as you can see from test cases at https://github.com/flatgeobuf/flatgeobuf/blob/master/src/ts/geojson.spec.ts, serialize and deserialise should work.

**Comment by bjornharrtell** [comment]
I've added a roundtrip to disk in this node example - https://github.com/flatgeobuf/flatgeobuf/blob/master/examples/node/index.js.

It's your writing part that is wrong. I'm not sure why you are using appendFileSync and Buffer.from but that works too.. if you delete the file before running of course.

**Comment by bacloud22** [comment]
Thanks a lot for providing an example. I will try that. Yes I agree me neither I don't know I just used append like the default option to write something in a file (unconsciously)
Thanks again

**Comment by bjornharrtell** [comment]
Programming while unconscious is dangerous. 😜
