### ISSUE TITLE
Streaming write in JavaScript/TypeScript

### ISSUE THREAD

**Issue by chrispahm** [flatgeobuf/flatgeobuf#223]
Thanks for developing this awesome geo format!

I was wondering if it's possible to also stream write in (Node/Deno) JS?
The only example I could find was using the Rust implementation
https://docs.rs/flatgeobuf/latest/flatgeobuf/#writing-a-flatgeobuf-file

Thanks!

**Comment by bjornharrtell** [comment]
Hi and thanks.

Correct, there is no streaming write done in the reference TypeScript code at this time. But considering https://github.com/flatgeobuf/flatgeobuf/blob/37af51ba2338219e7ff518f83a0e24c5cec9401f/src/ts/generic/featurecollection.ts#L25 it should not very hard to implement.

**Comment by chrispahm** [comment]
Alright, thanks for the pointer! Will have a look at that.
