### ISSUE TITLE
flatgeobuf-geojson.min.js  Uncaught (in promise) Error: Unknown type 9

### ISSUE THREAD

**Issue by Paradox98** [flatgeobuf/flatgeobuf#227]
flatgeobuf@3.22.0/dist/flatgeobuf-geojson.min.js

When the field type in the feature is Float, using js lib deserialize will throw an exception. `Uncaught (in promise) Error: Unknown type 9`.

I think it is necessary to support float type fields.

**Comment by bjornharrtell** [comment]
Good catch, it is simply an oversight in the implementation and I agree it should be fixed.

**Comment by bjornharrtell** [comment]
@Paradox98 I've released npm package 3.23.1 that includes the fix for this.
