### ISSUE TITLE
The logic to generate the Hilbert tree is not provided in java code.

### ISSUE THREAD

**Issue by Paradox98** [flatgeobuf/flatgeobuf#229]

**Comment by bjornharrtell** [comment]
Yes, never got to implement so can be regarded missing features that would be nice to get done at some point.

**Comment by Paradox98** [comment]
But I want the generated fgb to support the spatial filtering function. My development code is java, what do you suggest?

**Comment by bjornharrtell** [comment]
I suggest you implement/port it for Java and contribute if you like. Or get someone else to do it for you. :)

**Comment by Paradox98** [comment]
Which language has the relevant code currently implemented?

**Comment by bjornharrtell** [comment]
Currently cpp and rust.

**Comment by Paradox98** [comment]
thx

**Comment by ChenyuWang98** [comment]
https://github.com/SuperMap/flatgeobuf/tree/3.22.2-sm java code

**Comment by bjornharrtell** [comment]
@ChenyuWang98 nice, looking forward to PR! :)
