### ISSUE TITLE
[docs] How does flatgeobuf differ from geobuf?

### ISSUE THREAD

**Issue by nyurik** [flatgeobuf/flatgeobuf#236]
GeoBuf is mentioned in the main [docs page](https://flatgeobuf.org/), but there is not explanation how flatgeobuf differ from it, and what are the advantages/disadvantages. Thanks!

**Comment by bjornharrtell** [comment]
I feel the main docs page should be as condensed as possible so I don't think it's that place to dive into this subject. But here are some facts from the top of my head about geobuf that makes it different:

* Nearly lossless
* Optimized for size not speed
* Require two pass encoding to determine needed precision
* Require encoding and decoding (not zero copy)
* Not suitable for streaming
* No spatial index

**Comment by nyurik** [comment]
@bjornharrtell thanks!  Could you clarify if you were describing geobuf or flatgeobuf?  I presume the former in each case, but could be mistaken.

**Comment by bjornharrtell** [comment]
@nyurik the bullet points are for geobuf 😄
