### ISSUE TITLE
Example Dataset UScounties.fgb contains invalid Utf-8 byte sequences

### ISSUE THREAD

**Issue by M-DeRosier** [flatgeobuf/flatgeobuf#259]
The sample dataset https://github.com/flatgeobuf/flatgeobuf/blob/master/test/data/UScounties.fgb contains a number of byte values > 127 with no continuation bytes. These values are in the names of counties in Puerto Rico. Likely this came from converting the Shapefile directly to FlatGeobuf without transcoding from Windows-1252.
This contradicts the claim that FlatGeobuf strings are Utf-8 encoded and sample datasets provided should probably be in the correct encoding.

**Comment by M-DeRosier** [comment]
It appears the GDAL driver will transcode to Utf-8 as long as the incoming strings are _correctly_ tagged with the encoding.
I have regenerated the file by re-tagging string values as Windows-1252 and the GDAL driver produces correct Utf-8 output without prompting.
[US__counties.zip](https://github.com/flatgeobuf/flatgeobuf/files/10981952/US__counties.zip)

**Comment by bjornharrtell** [comment]
I'm curious, how do you do this re-tagging?

**Comment by bjornharrtell** [comment]
I've commited your fixed file with https://github.com/flatgeobuf/flatgeobuf/commit/3f59f2950ac495332004a1623ce9cf51fc658c2c, thanks @M-DeRosier.

**Comment by M-DeRosier** [comment]
An FME 2023.0 beta.
