### ISSUE TITLE
Java PackedRTree inefficient streaming search

### ISSUE THREAD

**Issue by aaime** [flatgeobuf/flatgeobuf#274]
The streaming search re-sorts the entire Stack it's using after each insertion, which makes it rewrite the entire backing data structure. A PriorityQueue is designed to insert new items in the right order without as much overhead.

**Comment by bjornharrtell** [comment]
After some recollection and thinking I think that sort was added by mistake for some reason. I do not believe it is needed as the flatgeobuf index is guaranteed to be sorted already.

I've made https://github.com/flatgeobuf/flatgeobuf/pull/277 that removes the sort and replace Stack with Deque.

**Comment by bjornharrtell** [comment]
I'll try to get this out in a patch release later today and then do downstream patches.
