### ISSUE TITLE
Migrate CI to GH Actions?

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#280]
Currently we use circle-ci to run tests for pull requests.

My understanding of how this works is that circle ci will interact with github, authenticating as the PR author. 

This means the PR author needs to create a circle ci account, and authorize it via GH's oauth.

And apparently it needs a lot of access:
![list of permissions requested, including read/write access to all public and private repos](https://user-images.githubusercontent.com/217057/254679224-3d796d77-4361-43b5-9256-55f3b13d0cc0.png)

Using github actions would remove this requirement. Would you be interested in switching?

It's totally fair if you'd rather stay with circle-ci. I'm actually kind of sympathetic to the fact that it may very well be GH's API limitations that don't allow external CI providers to do the right thing, but at the end of the day, it'd be nice if I could use CI without handing out all the keys to all my castles to a third party service.

If you're interested, I can spend some time trying to translate the circle-ci config to a GH actions config.

**Comment by bjornharrtell** [comment]
@michaelkirk yep I have no objections to migrating to GitHub Actions. I do agree that there is a risk that GitHub is indeed killing off competitors like CircleCI and that's sad... but not my fight.
