### ISSUE TITLE
Build error in windows 10 for the Config.js and Logger.js issue

### ISSUE THREAD

**Issue by xiaoq7758** [flatgeobuf/flatgeobuf#284]
![image](https://github.com/flatgeobuf/flatgeobuf/assets/8068508/35a91060-57de-4eed-8e49-64a6242443bf)
in windows 10 build will miss load the config.js and logger.js.  And see the File is Config.js and Logger.js
and has change the code same filename with the file it build success

**Comment by bjornharrtell** [comment]
This is more than a year old version. Please using latest version and from scratch (clean node_modules etc). Feel free to reopen if issue persists after that.
