### ISSUE TITLE
[Q] concatenating flategeobuf files?

### ISSUE THREAD

**Issue by kkdd** [flatgeobuf/flatgeobuf#292]
Hello,
How to concatenate/merge flategeobuf files, in the same way as ```geojsonl(.gz)``` files?

Note that they are concatenated by using ```cat```:
```
$ cat each*.geojsonl.gz > merged.geosonl.gz
```

Thank you.

**Comment by bjornharrtell** [comment]
Not possible. You can append feature data on unindexed flatgeobuf but that needs to be done at lower level than cat.

**Comment by kkdd** [comment]
Dear bjornharrtell,
Thank you for your advice.
I wish some solutions for concatenating/merging, in the future, by the way.

**Comment by michaelkirk** [comment]
Support for merging FGBs would be great. 

In the meanwhile, just in case it wasn't obvious, you can convert fgb to some other better supported format, merge that, and convert back.

**Comment by kkdd** [comment]
Dear michaelkirk,
Thank you for your comment.
Can you present any ways for merging, in the present status.
Thank you.

**Comment by bjornharrtell** [comment]
One option is to use GDAL, see https://gdal.org/programs/ogrmerge.html.

**Comment by kkdd** [comment]
Thank you for your advice.
