### ISSUE TITLE
Failing to read empty FlatGeobuf with Java

### ISSUE THREAD

**Issue by aaime** [flatgeobuf/flatgeobuf#312]
Given an empty FlatGeobuf file, as per ogrinfo output:

```
INFO: Open of `/...emptyFlatGeoBuf.fgb'
      using driver `FlatGeobuf' successful.

Layer name: SELECT
Geometry: Point
Feature Count: 0
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["unknown",
        ELLIPSOID["WGS84",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
wind_speed: Real (0.0)
wind_direc: Real (0.0)
backscatte: Real (0.0)
```

The Java library would fail to read it instead:

```
Caused by: java.lang.RuntimeException: Node size must be at least 2
	at org.wololo.flatgeobuf.PackedRTree.generateLevelEnds(PackedRTree.java:199)
	at org.wololo.flatgeobuf.PackedRTree.search(PackedRTree.java:337)
	at org.geotools.data.flatgeobuf.FeatureCollectionConversions.deserialize(FeatureCollectionConversions.java:139)
	at org.geotools.data.flatgeobuf.FlatGeobufFeatureReader.<init>(FlatGeobufFeatureReader.java:104)
```

An empty FGB does not make much sense, but it can happen while bulk processing data (splitting it over attributes to work around the lack of alphanumeric indexes).

**Comment by bjornharrtell** [comment]
Agreed this is a bug. The likely reason for it is because initially I thought to forbid empty FlatGeobuf but have since eased up on that. :)

**Comment by bjornharrtell** [comment]
But hmm, not sure the bug is here. It shouldn't attempt to use PackedRTree in this case.

**Comment by bjornharrtell** [comment]
Yep, logic at https://github.com/geotools/geotools/blob/ffdf418ad09dc20eb8a15caa709c72d4c409017f/modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java#L124 is too naive. Optimally it should handle featuresCount = 0 as potentially (0 = unknown) empty file and return an empty iterator if there is no data after the header. If there is data it is an unindexed file and must iterate the whole file and apply rect filter as secondary. It can also be featuresCount > 0 but indexNodeSize == 0 which means it is an unindexed file with known feature count and must also be treated as the unindexed case.

**Comment by bjornharrtell** [comment]
I've made https://osgeo-org.atlassian.net/browse/GEOT-7457 to track this in geotools
