### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by sebakerckhof** [flatgeobuf/flatgeobuf#320]
Hi, would it be possible to release a new version?
Since the currently published version on npm is not compatible with OL 8 (due to peer dependency requirements), but this has already been adjusted: https://github.com/flatgeobuf/flatgeobuf/commit/7d28414f5d409c0a1f4953214a5596131baec2dd

**Comment by bjornharrtell** [comment]
Yes it would be possible.

**Comment by bjornharrtell** [comment]
@sebakerckhof 3.27.0 is published - I would appreciate feedback if it works as it should, I haven't yet had the chance to actually use this as a proper dependency in a project that uses ol 8.

**Comment by sebakerckhof** [comment]
Thanks, seems to work fine with OL8 in my project.
