### ISSUE TITLE
Link alternative GoLang implementation from flatgeobuf.org?

### ISSUE THREAD

**Issue by vcschapp** [flatgeobuf/flatgeobuf#326]
Would you consider linking out from `flatgeobuf.org` to an alternative Go implementation of the FlatGeobuf format? (Note: I'm the author.)

The library is found at https://github.com/gogama/flatgeobuf

It takes a slightly different approach to the problem from the official Go version that was just released in September, so it potentially gives end-users an extra set of options to choose from when they're looking to build Go-based software using Flatgeobuf, and ideally expands the ecosystem!

I've just cut a release tag today, `v0.9.0-alpha`, and plan to have a stable `v1.0.0` within a few months. The only thing in the way is a vacation I'm taking. Hoping increased visibility from `flatgeobuf.org` might generate feedback that I can use to tweak the API and docs for usability before the stable release.

-----

We had a short technical discussion about sort order [in June](https://github.com/flatgeobuf/flatgeobuf/discussions/271) when I was in the middle of implementing, before the official version came out in September, but I got busy with other things and didn't keep the momentum up. I got re-inspired when some colleagues found my library and indicated they like the flexibility of the API. They currently plan to use it to solve a pretty neat problem at scale.

**Comment by bjornharrtell** [comment]
Thanks for your efforts @vcschapp!

I've added a link to https://github.com/flatgeobuf/flatgeobuf/blob/master/README.md#supported-applications--libraries.

My Go experience and usage is almost nonexistent, but I'm inclined to say the more the merrier. Do you want to chime in @bruno-ga?

**Comment by brunoga** [comment]
Sorry I did not reply sooner. I am on vacations until next week (so replying with my personal account). I will check that alternative implementation but, in principle, I am perfectly fine with multiple implementations as long as they do not start causing confusion at some point in time.

**Comment by brunoga** [comment]
As an addendum to that, @vcschapp can feel free to contribute to the in-repo version, of course. :)

**Comment by vcschapp** [comment]
Thank you @bjornharrtell!
