### ISSUE TITLE
Inefficient chunking for dense/urban dataset

### ISSUE THREAD

**Issue by mariogiampieri** [flatgeobuf/flatgeobuf#343]
Thank you for your work on this- it's one of the most exciting projects I've come across in a while! I am attempting to integrate into a node project but am having an issue with extremely uneven chunk sizes being read from a Cloudflare endpoint. 

<img width="1243" alt="image" src="https://github.com/flatgeobuf/flatgeobuf/assets/11448308/79fb1af0-c6fa-487f-a0e9-b50feb02c171">
 
In this test, I do not initiate `geojson.deserialize()` on the source until the map zoom reaches 14. However, I still see what amounts to the entire file loading at that point. The file's coverage is much larger than the canvas area at zoom level 14 and is 216mb total. I have tested with smaller extracts of this file, as well as other files, and see similar behavior where the majority of the file's size is held in 1-2 chunks.  These files were prepared using `ogr2ogr -f FlatGeobuf -dsco SPATIAL_INDEX=YES out.fgb input.geojson`, explicitly setting the spatial index. As a sanity check I also tried converting using `pyogrio` despite that essentially just wrapping the above function.

I did also try converting the `counties` shapefile in the examples dir and serving that, as well as serving the example `UScounties.fgb` from my Cloudflare bucket with no issue- in each case, I see reasonably-sized chunks coming in. 

My question is whether this issue is because of a) the scale of my data (dense, urban) and the amount of data held in each byte range being so large, b) some user error on my part in converting data to `fgb`, c) the bounding rect not being respected for some reason, or d) some other user error. My guess is some combination of b, c, and d. 

Any insight you have would be greatly appreciated! I'm using version `3.27.2`.

**Comment by bjornharrtell** [comment]
I have no obvious explanation. Are you sure bbox used as filter is really what you expect? As you can see in example https://flatgeobuf.org/examples/openlayers/large.html with 12GB file it should work. The format itself should not allow for a "suboptimal" conversion so I would guess the problem lies elsewhere.

**Comment by bjornharrtell** [comment]
PS. FlatGeobuf does not have chunks. The spatial index search will return individual feature offsets and the logic will concatenate the hits into a single range if possible. So what you see should only be possible due to that you hit all of your features (or have a few *very* large features).

**Comment by mariogiampieri** [comment]
Apologies for the imprecise language regarding chunks- thank you for clarifying. Your comment allowed me to identify my error- the search area composed in the example `fgBoundingBox()` function did include my entire search area and so was causing the entire file to be loaded. I am now using a different bbox function to grab more reasonable extents based on my use case. Thanks for the help / speedy response and all of your work on this!
