### ISSUE TITLE
Avoid blinking

### ISSUE THREAD

**Issue by kochizufan** [flatgeobuf/flatgeobuf#346]
Hi, thank you for nice product!

But it is somehow dissapointment that features are blinking (it looks clear all and add all) in filtered case.
https://[flatgeobuf.org/examples/openlayers/filtered.html](https://flatgeobuf.org/examples/openlayers/filtered.html)
I read source code but I can't understand how to achieve this.

Is it possible?
If not, I want to have it as new feature.

**Comment by michaelkirk** [comment]
It took me a second to understand what you meant - it seems specific to the openlayers demo.

The leaflet example doesn't exhibit the problem you're reporting, right? https://flatgeobuf.org/examples/leaflet/filtered.html

I'm not familiar with openlayers, but it looks like we're triggering a reload right after the initial load:
<img width="1150" alt="Screenshot 2024-02-07 at 11 14 34" src="https://github.com/flatgeobuf/flatgeobuf/assets/217057/083da3f0-91fa-42dc-89cd-1b7c7e8367a4">

**Comment by bjornharrtell** [comment]
I've reworked the logic to what I think is the better way and it doesn't blink anymore.

**Comment by michaelkirk** [comment]
Confirmed that the redundant load is gone. 👍
