### ISSUE TITLE
Occasional flatgeobuf-geojson.min.js GET http://localhost/some.fgb net::ERR_CACHE_OPERATION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by qitMiro** [flatgeobuf/flatgeobuf#354]
Thank you for amazing flatgeobuf. Seems we finally have something after decades of dealing with shapefiles. Can't wait for adoption by mainstream GIS. I am getting occasional GET http://localhost/some.fgb net::ERR_CACHE_OPERATION_NOT_SUPPORTED with **flatgeobuf-geojson.min.js**. Not sure if I am doing something wrong. I am getting this error in both Chrome and Edge. The frequency of this error might be correlating with number of features being fetched but I do get it anywhere between fetching a couple hundred to tens of thousands.

> GET http://localhost/shared/qld/qld-dcdb.fgb net::ERR_CACHE_OPERATION_NOT_SUPPORTED
getRange @ flatgeobuf-geojson.min.js:15
getRange @ flatgeobuf-geojson.min.js:15
readFeature @ flatgeobuf-geojson.min.js:15
readFeatureBatch @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
E @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
E @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
(anonymous) @ flatgeobuf-geojson.min.js:15
Y @ flatgeobuf-geojson.min.js:15
t.next @ flatgeobuf-geojson.min.js:15
selectBbox @ flatgeobuf-geojson.min.js:15
await in selectBbox (async)
(anonymous) @ flatgeobuf-geojson.min.js:15
flatgeobuf-geojson.min.js:15 

> Uncaught (in promise) TypeError: Failed to fetch
    at pt.getRange (flatgeobuf-geojson.min.js:15:20070)
    at ft.getRange (flatgeobuf-geojson.min.js:15:19425)
    at dt.readFeature (flatgeobuf-geojson.min.js:15:18667)
    at dt.readFeatureBatch (flatgeobuf-geojson.min.js:15:18536)
    at readFeatureBatch.next (<anonymous>)
    at Function.<anonymous> (flatgeobuf-geojson.min.js:15:10825)
    at flatgeobuf-geojson.min.js:15:1510
    at Object.next (flatgeobuf-geojson.min.js:15:1615)
    at flatgeobuf-geojson.min.js:15:552
    at new Promise (<anonymous>)

**Comment by bjornharrtell** [comment]
I've not seen this issue. Sure it's not an issue with your local webserver?

**Comment by qitMiro** [comment]
> I've not seen this issue. Sure it's not an issue with your local webserver?

Thank you for quick reply. Might be my misunderstanding of what cache this error talks about. I thought it is about browser cache. I will do some more testing including AWS servers after I deploy from local to dev and come back with findings.

**Comment by bjornharrtell** [comment]
Closing due to lack of feedback/activity.
