### ISSUE TITLE
Does flatgeobuf uses http range requests?

### ISSUE THREAD

**Issue by am2222** [flatgeobuf/flatgeobuf#360]
Hi,

I was wondering if this library uses httprange requests to fetch header and features. Mainly something similar to pmtiles.

**Comment by michaelkirk** [comment]
It does if you are using the bbox API to select a subset of features. Search the readme for "Range" and there's a little bit about it. 

The rust client actually uses range requests for the "select all" case as well as it's buffering strategy.
