### ISSUE TITLE
[rust] Can't upgrade to reqwest 0.12.x

### ISSUE THREAD

**Issue by bjornharrtell** [flatgeobuf/flatgeobuf#367]
Getting " ^^^^^ the trait `AsyncHttpRangeClient` is not implemented for `Client`"

**Comment by michaelkirk** [comment]
Is this due to #366? My first guess is that there is some version specification we need to bump.

Is there a Cargo.lock you can share?

**Comment by michaelkirk** [comment]
I'm taking a look at this now. 

(related: https://github.com/flatgeobuf/flatgeobuf/pull/351)

**Comment by michaelkirk** [comment]
The proximate cause of the error is that we use http-range-client which wraps reqwest, so we need to update that crate's reqwest dependency first.

...which is not quite trivial because something has broken the wasm build for http-range-client. So I'm looking at that too.
