### ISSUE TITLE
how to render a planar coordinate FlatGeobuf data?

### ISSUE THREAD

**Issue by sendreams** [flatgeobuf/flatgeobuf#370]
I have stored some planar coordinate data using FlatGeobuf, which can be understood as CAD data. What front-end tools are available to display this data? Can it be displayed using front-end tools like OpenLayers? I understand that GIS tools like OpenLayers require coordinate information.

**Comment by bjornharrtell** [comment]
Yes.

**Comment by sendreams** [comment]
From what I understand, to display planar coordinates using OpenLayers, the coordinates need to be converted to the UTM coordinate system first. However, my data is just regular planar coordinates and cannot be converted. Is it really possible?

**Comment by bjornharrtell** [comment]
Why are you asking questions about OpenLayers here? There is no requirement to use UTM coords in OpenLayers, check out example https://openlayers.org/en/latest/examples/static-image.html.

**Comment by sendreams** [comment]
@bjornharrtell very thanks.
