### ISSUE TITLE
[ts] Error [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by XiaoYang943** [flatgeobuf/flatgeobuf#373]
Hello,please help me! Thanks!

**Here is my code:**
import { geojson } from 'flatgeobuf'

**Here is the error:**
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '\node_modules\flatgeobuf\lib\mjs\geojson\feature' 

**Here is dependence:**
"dependencies": {
    "ol": "^9.2.4",
    "vue": "^3.4.21",
    "flatgeobuf": "3.32.0",
    "node-fetch": "^3.3.2"
  }

**Comment by bjornharrtell** [comment]
Problem was incorrect handling of interface/type imports in TypeScript. Not sure why typecheck isn't catching them but anyhow I believe it's fixed as of 3.32.3.

**Comment by XiaoYang943** [comment]
ok. Thanks! It was fixed!
