### ISSUE TITLE
[go] trivial ergonomics improvement

### ISSUE THREAD

**Issue by dzfranklin** [flatgeobuf/flatgeobuf#384]
The interface `writer.FeatureGenerator` can somtimes be satisfied with a simple function. This is analogous to the standard library `http.Handler`. By defining a type alias like so it would be slightly easier to use in the trivial case.

```go
type FeatureGeneratorFunc func() *Feature

func (f FeatureGeneratorFunc) Generate() *Feature {
	return f()
}
```

usage

```go
features := *writer.Feature[]{...}
fgen := writer.FeatureGeneratorFunc(func() *Feature {
    return features
}
```

For example this would slightly simplify your test cases.

**Comment by brunoga** [comment]
That is a good idea. Feel free to send a PR. :)

**Comment by dzfranklin** [comment]
I don't know what I was thinking. This can't work because of the need for internal state tracking the iteration progress.

**Comment by brunoga** [comment]
FWIIW, for simple cases it would work. Yes, the reason for the current pattern is because in the common case you are going to keep state but it is not impossible to have a stateless generator. State can also be kept in other ways like around the closure itself or, God forbid, globals. :)
