### ISSUE TITLE
fgb https deserialize AyncGenerator with bbox, results in correct number of features but wrong items

### ISSUE THREAD

**Issue by beckietech** [flatgeobuf/flatgeobuf#388]
document.addEventListener("DOMContentLoaded", async () => { 
            //for await (const f of flatgeobuf.deserialize(response.body))
                //L.geoJSON(f).bringToFront().addTo(map);
                ////////////////
            // optionally show some meta-data about the FGB file
            function handleHeaderMeta(headerMeta) {
                const header = document.getElementById('header')
                const formatter = new JSONFormatter(headerMeta, 10)
                while (header.firstChild)
                    header.removeChild(header.firstChild)
                header.appendChild(formatter.render())
            }

            // For the example, we fix a visible Rect representing the query
            // bounding box in the middle of the map
            function getBoundForRect() {
                //console.log(map.getCenter());
                const widthMeters = 200;
                return map.getCenter().toBounds(widthMeters);
            }

            // convert the rect into the format flatgeobuf expects
            
            function fgBoundingBox() {
            bounds = turf.bbox(buffered1);//getBoundForRect();
                return {
                    minX: bounds[0],//.getWest(),minY:bounds[1],//
                    minY: bounds[1],//.getSouth(),minX:bounds[0],//
                    maxX: bounds[2],//.getEast(),maxY:bounds[3],//
                    maxY: bounds[3],//.getNorth(),maxX:bounds[2],//
                }
            }

            bboxObjectToArray = (obj) => [
                [obj.minY, obj.minX],
                [obj.maxY, obj.maxX],
            ];

  // show a leaflet rect corresponding to our bounding box
            //let rectangle = L.rectangle(getBoundForRect(), { interactive: false, color: "blue", fillOpacity: 0.0, opacity: 1.0 }).addTo(map);
            //rectangle.bringToFront();
            // track the previous results so we can remove them when adding new results
            let previousResults = L.layerGroup().addTo(map);
            async function updateResults() {
                // remove the old results
                previousResults.remove();
                const nextResults = L.layerGroup().addTo(map);
                previousResults = nextResults;
                //console.log(nextResults);
                // Use flatgeobuf JavaScript API to iterate features as geojson.
                // Because we specify a bounding box, flatgeobuf will only fetch the relevant subset of data,
                // rather than the entire file.
                const colorScale = ((d) => {
                    return d > 750 ? '#800026' :
                        d > 500 ? '#BD0026' :
                        d > 250  ? '#E31A1C' :
                        d > 100 ? '#FC4E2A' :
                        d > 50   ? '#FD8D3C' :
                        d > 25  ? '#FEB24C' :
                        d > 10   ? '#FED976' :
                        '#FFEDA0'
                });
                iter = flatgeobuf.deserialize('/data/Gy_A_rice_weight_UTMz51_1.fgb', fgBoundingBox(), handleHeaderMeta);
                const results = L.layerGroup().addTo(map);
                for await(const feature of iter){console.log(feature);
                    features = { type: "FeatureCollection", features: [] };
                    features.festures.push(feature);
                    // Leaflet styling
                    const defaultStyle = { 
                        color: colorScale(feature.properties["Area"]), 
                        weight: 1, 
                        fillOpacity: 0.4,
                    };
                    L.geoJSON(feature, {
                        style: defaultStyle,
                    }).on({
                        'mouseover': function(e) {
                            const layer = e.target;
                            layer.setStyle({
                                weight: 4,
                                fillOpacity: 0.8,
                            });
                        },
                        'mouseout': function(e) {
                            const layer = e.target;
                            layer.setStyle(defaultStyle);
                        }
                   }).bindPopup(`${feature.properties["Area"]} people live in this census block.</h1>`)
                   .addTo(nextResults);
                }
                let rectangle = L.rectangle(bboxObjectToArray(fgBoundingBox()), {
    interactive: false,
    color: "blue",
    fillOpacity: 0.1,
    opacity: 1.0,
  }).addTo(map);
                rectangle.bringToFront();
            }
            // if the user is panning around alot, only update once per second max
            updateResults = _.throttle(updateResults, 10);
            
            // show a leaflet rect corresponding to our bounding box
            //let rectangle = L.rectangle(getBoundForRect(), { color: "blue", fillOpacity: 0.7, opacity: 1.0 }).addTo(map);
            // Render the bounding box rectangle
  
            //rectangle.bringToFront();
            // show results based on the initial map
            updateResults();
            // ...and update the results whenever the map moves
            map.on("moveend", function(s){
                rectangle.setBounds(getBoundForRect());
                updateResults();
            });
        });
![1](https://github.com/user-attachments/assets/a8d4ccb5-d805-4d12-86cb-eb20d8628040)
![2](https://github.com/user-attachments/assets/2159bfa4-8b23-4cf6-91ff-a7e0a5c1d5a9)
[1]:shows AsyncGenerator Results
[2]:shows correct output

I'm only a few days looking into this library, please help me !! thanks

**Comment by bjornharrtell** [comment]
Do you think there is a problem in this library? I'm not convinced by that code dump. Perhaps if you can reproduce as a self contained example including data at fx https://codepen.io/.

**Comment by beckietech** [comment]
Since I'm new to this library, and I suspected the error came from leaflet transpose/fgb generating from shp crs issue, but none of them helps... I'm using test code of samples online and still not able to get correct outcome. Thanks!!

**Comment by michaelkirk** [comment]
Make sure you're specifying your bounding box in the correct order.

**Comment by beckietech** [comment]
@michaelkirk thanks, could you tell me the right sequence?

**Comment by michaelkirk** [comment]
Check out the example code at https://flatgeobuf.org/examples/maplibre/filtered.htmlOn Oct 16, 2024, at 17:11, beckietech ***@***.***> wrote:﻿
@michaelkirk thanks, could you tell me the right sequence?

**Comment by beckietech** [comment]
@michaelkirk thank you for prompt reply! I tried using return { minX: lng-size, minY: lat-size, maxX: lng+size, maxY: lat+size } kind of sequence, it did help me get into upadateResults loop, it turned out I was only looking into the worng result at first place. however, the ourcome number shrink to only one feature ... I will keep looking for something wrong with it...

**Comment by beckietech** [comment]
@bjornharrtell I'm facing an issue that although I can check layers with map._layers, and the features are in it. I can't make them appear on the map even though I use setZIndex or style.z-index. Can you shed some lights of how to solve this? Thanks in advance...

**Comment by bjornharrtell** [comment]
Sorry I can't provide assistance with general leaflet usage.

Closing as I see no evidence of a bug.
