### ISSUE TITLE
Using FlatBufferBuilder on Windows results in an error

### ISSUE THREAD

**Issue by w345731923** [flatgeobuf/flatgeobuf#398]
Using PostGIS with multithreading works fine on Linux, but it gets stuck on the Windows platform.

Even a simple declaration like the following seems to affect lwerror error throwing:

In _c.cpp:
FlatBufferBuilder fbb;
Offset<Geometry> geometry = 0;
Offset<Vector<uint8_t>> properties = 0;

In _pg.c:
ereport(ERROR, (errmsg_internal("%s", errmsg)));

Any ideas or solutions to address this issue?

**Comment by bjornharrtell** [comment]
No idea but seems more related to flatbuffers than flatgeobuf. Feel free to reopen if you find some more evidence that it's caused by something related to flatgeobuf.
