### ISSUE TITLE
can flatgeobuf rust code could compile to wasm use in browser ?

### ISSUE THREAD

**Issue by xilanhuaweidapao** [flatgeobuf/flatgeobuf#399]
i try to compile to wasm, it can success, but don't export useful function, who is have good performace between compile to wasm and ts version ?

**Comment by pka** [comment]
AFAIK, this has not been tested yet. I wouldn't expect a notable difference between WASM and Javascript, because decoding Flatbuffers should be neglectable compared to reading data over HTTP.
