### ISSUE TITLE
Optimize I/O for JavaScript implementation

### ISSUE THREAD

**Issue by bjornharrtell** [flatgeobuf/flatgeobuf#50]
Prior art is the general prefetch strategy in GDAL, see https://gdal.org/user/virtual_file_systems.html#vsicurl-http-https-ftp-files-random-access.

**Comment by kylebarron** [comment]
Is your idea to retrieve the beginning metadata and then potentially use range requests to read portions of the rest of the file? That's a strategy used for Cloud Optimized Geotiffs.

**Comment by bjornharrtell** [comment]
The current implementation already does that on filtered access but a bit too naively, see https://github.com/bjornharrtell/flatgeobuf/blob/0ce5c837491a41a0f6771ab150bbd7eb0e9a8c26/src/ts/generic/featurecollection.ts#L87-L91.

The problem with the naive approach is that it can result in many small requests. What this issue is about is about using a generic prefetch strategy to reduce the amount of requests, which is what GDAL does.

**Comment by pka** [comment]
The performance win for buffered http access is huge! In the Rust driver I've added a buffer to the http client and an additional `get` method with a `min_req_size` parameter:
https://github.com/bjornharrtell/flatgeobuf/blob/master/src/rust/src/http_reader.rs#L59
It's currently set to 512B for header access, the full index size for index access and to 1MB for data access.

**Comment by bjornharrtell** [comment]
@pka that `BufferedHttpClient` seems very clever. :)

**Comment by michaelkirk** [comment]
Some related work for the rust client in #93

**Comment by michaelkirk** [comment]
After fixing the bbox'd example in #114, I was surprised to see that FGB made 50 requests to render the 17 features.

<img width="2032" alt="Screen Shot 2021-04-24 at 7 04 25 PM" src="https://user-images.githubusercontent.com/217057/115977782-f0630800-a52f-11eb-833b-942d0067e6bb.png">

Is that surprising, and covered by the work you anticipated doing here, or do you suspect that is another bug and I should open a separate issue?

**Comment by bjornharrtell** [comment]
@michaelkirk current implementation is very naive about I/O so it is not unexpected and it is what this issue is about.

**Comment by michaelkirk** [comment]
Ok, that makes sense, just wanted to make sure.

Would you be interested in a typescript implementation similar to what I did for rust in #93? This is something I'd be interested in working on.

**Comment by bjornharrtell** [comment]
Absolutely, much appreciated!

**Comment by michaelkirk** [comment]
My current approach is to work towards something like we have in the Rust implementation, which is predicated on the buffered reader that @pka built.

All in all, it's shaping up to be a pretty large PR. I'm not nearly done yet, but I'd estimate a diff in the 500-1k line range. Does that seem reasonable @bjornharrtell? 

I just wanted to check in on your expectations before I get too invested.

**Comment by bjornharrtell** [comment]
Seems ok to me. Your strategy is fairly complex but I believe you have proven it is worth it.
