### ISSUE TITLE
Create a flatgeobuf organization

### ISSUE THREAD

**Issue by pka** [flatgeobuf/flatgeobuf#95]
The Julia implementation #88 seems a good reason to think about collecting flatgeobuf repos in its own organization. The support of flatgeobuf gets broader and a Github organization would reflect that better, IMHO.

@evetion: Would you support moving your Julia implementation to a common organization?

**Comment by bjornharrtell** [comment]
Hey @pka that is a great idea. :)

**Comment by bjornharrtell** [comment]
Done at https://github.com/flatgeobuf. I will move this repo after thinking about consequences a bit.

**Comment by michaelkirk** [comment]
You're probably already aware, but just in case:

If you do this, it's probably best to do something like described here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository 

To make sure issues etc. get moved to the new location.

**Comment by pka** [comment]
Thanks @bjornharrtell! Moving a repo to an org is quite painless in my experience. Github redirects old URLs for a long time. The most obvious consequence I see is a new homepage URL. But it would deserve its own domain name like flatgeobuf.org anyway?

**Comment by evetion** [comment]
I'm open to moving to an organization. It's a common practice in Julia, see https://github.com/JuliaGeo for example, but only if the package has become mature, so multiple people can easily do (required) maintenance. Not sure if that would hold for flatgeobuf. I'll await @bjornharrtell decision.

**Comment by bjornharrtell** [comment]
Done!

@evetion I don't feel an implementation needs to be "mature" to be hosted under the organization, so if you want to move it there feel free to.
